### PR TITLE
VACMS-13649: Multi-time pattern passthrough

### LINKED ISSUE #13649: VBA multi-time pattern is not properly parsed by migration
## Describe the defect
We have some VBA facilities that now have multiple time ranges per day.  
```
"hours": {
                    "Friday": "8:30 a.m. - 12:00 p.m., 1:00 p.m - 4:00 p.m.",
                    "Monday": "Closed",
                    "Sunday": "Closed",
                    "Tuesday": "8:30 a.m. - 12:00 p.m., 1:00 p.m - 4:00 p.m.",
                    "Saturday": "Closed",
                    "Thursday": "8:30 a.m. - 12:00 p.m., 1:00 p.m - 4:00 p.m.",
                    "Wednesday": "8:30 a.m. - 12:00 p.m., 1:00 p.m - 4:00 p.m."
                },
```
Our migration parser is not properly breaking them into either separate entries or dumping the second entry to comments.  Currently it is taking the first start and the last closed and using those while discarding the middle.
  "Friday": "**8:30 a.m.** - 12:00 p.m., 1:00 p.m - **4:00 p.m.**",

## To Reproduce
1. Go to the entry for 'vba_339'  https://prod.cms.va.gov/node/4168/edit   see the times being used are not a fully accurate representation of the hours in the sample data above.

## AC / Expected behavior
- [ ] I expect when we encounter two time ranges, that the whole string is put into the comments
- [x] I expect that we validate that length of comments is not a limiting factor  (go to plan B instead: parsing the first time range and second into comments) -- After testing, the field accepts 255 characters, which is more than enough
- [ ] I expect the front end display is validated in tugboat 

## Additional context
This is unrelated to the issue of times showing appropriately on the Facility Locator.

This is specific to VBA data at the moment, but the parser is used by all facility migrations and it should be able to handle it correctly for all facility types.

The facilities with multiple sets of hours are
- vba_339
- vba_339b
- vba_339c

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #13649 

## Testing done
Manually

### Hours being parsed as hours
Screen Shot 2023-06-08 at 2 15 05 PM

### Hours being parsed as comments
Screen Shot 2023-06-08 at 2 20 11 PM

## QA steps
As user an admin user
- Run the [VBA migration](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_vba/execute)
- Open the terminal in the Tugboat environment
- Run the following:
  - `drush migrate:import va_node_facility_nca --update --idlist=nca_800`
  -  `drush migrate:import va_node_health_care_local_facility --update --idlist=vha_557`
- Validate that the following have been formatted and put into comments:
  - [x] [vba_339](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4168/edit)
  - [x] [vba_339b](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4170/edit)
  - [x] [vba_339c](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/48912/edit)
- Validate that the following have not regressed (compared to the Lighthouse api)
  - [x] [vha_557](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/1484/edit): "24/7"
  - [x] [vba_307](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/3955/edit): "By appointment only"
  - [x] [vba_307b](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/3957/edit): No space after start time and "a.m."
  - [x] [vba_311a](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/42635/edit): Multi-range hours
  - [x] [vba_316](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4014/edit): No period after "a.m"
  - [x] [vba_317](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4029/edit): No space after "a.m."
  - [x] [vba_320a](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4073/edit): Includes "12:00 p.m." in end date (check that it's not midnight)
  - [x] [vba_327](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4115/edit): Includes "12:00 p.m." in start date (check that it's not midnight)
  - [x] [vba_347](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4233/edit): Uppercase "AM" and "PM"
  - [x] [vba_348](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4237/edit): No space before "am" or "pm"
  - [x] [vba_348a](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4238/edit): Odd data that should be put into a comment
  - [x] [vba_349u](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4267/edit): Has "to" instead of "-"
  - [x] [vba_442](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4338/edit): Inconsistent am/pm and spacing
  - [x] [vba_463c](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/node/4355/edit): Bad range character and leading zero

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### CODE REVIEW

File: docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php [hunk 1]
```diff
@@ -53,24 +53,29 @@ public function transform($value, MigrateExecutableInterface $migrate_executable
     ];
 
     foreach ($hours as $day => $hour) {
-      // Test $hour for non-contiguous entries, separated by semi-colons.
-      if (preg_match('(\;)', $hour) === 0) {
+      // Test $hour for non-contiguous entries,
+      // separated by semi-colons or comma.
+      if ((preg_match('(\;)', $hour) === 0)
+        && (preg_match('/(,\s\d)/', $hour) === 0)) {
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php:59]: I am a little nervous about making this hinge on a comma or semicolon.  Seems like it might be too sensitive a hair trigger.    Would it work to sum the count of AM and the count of PM?  Anything more than three triggers it?

File: docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php [hunk 2]
```diff
@@ -53,24 +53,25 @@ public function transform($value, MigrateExecutableInterface $migrate_executable
...
+      $hour = remove_leading_zeroes($hour);
       $low_day = strtolower($day);
-      if (preg_match('(AM|PM)', $hour) === 0) {
-        // It is not hours, treat it as a comment.
-        $hours_clean[$low_day]['comment'] = $hour;
-      }
-      else {
+      // Second, we parse the data.
+      if (parse_as_hour($hour)) {
+        // We have one start and one end time.
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php:62]: Super minor, no action required:  Just illustrating naming carrying clarity
These two lines could be replaced by 
` if (has_two_sets_of_hours($hour)) {`

File: docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php [hunk 3]
```diff
@@ -53,24 +53,25 @@ public function transform($value, MigrateExecutableInterface $migrate_executable
...
+        // Strip hour before the "to" for starthours.
+        $start_time = strstr($hour, 'to', TRUE);
+        // Strip hour after the "to" for endhours.
+        $end_time = strstr($hour, 'to');
         $hours_clean[$low_day]['start_time'] = clean_time($start_time);
         $hours_clean[$low_day]['end_time'] = clean_time($end_time);
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php:68]: I am feeling like we are missing grabbing anything that remains and putting it into the comment.
incoming: 9:00AM - 5:00PM Closed second Tues of the month.
stored:
- start_time = 9:00AM
- end_time = 5:00PM
- comment = null

When what we want is 
- start_time = 9:00AM
- end_time = 5:00PM
- comment = Closed second Tues of the month.

I swear we used to have that functionality.  Which is what might have allowed this to keep working as it was without needing to change anything.

Comment (swirtSJW) [reply docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php:68]: The other pattern we want to capture, which is why we only skip entry if there are more than 3 AMPMs  is 
9:00AM - 5:00PM Closed at 1:00PM for half hour lunch.

So if we pick off the first two times, we still want "Closed at 1:00PM for half hour lunch." to end up in the comments.

**Review by swirtSJW — COMMENTED** [review]
This is looking very good.   I have a few concerns that maybe are already covered in the code, but it seems like maybe not.

File: docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php (hunk 2 above)
Comment (omahane) [reply docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php:62]: I like this idea. I would suggest "has_one_set_of_hours", as a set implies a group.

File: docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php (hunk 3 above)
Comment (omahane) [reply docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php:69]: Discussed in [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1686164870673899). Resolved to not do, as the data do not warrant it.

**Review by swirtSJW — APPROVED** [review]
Fantastic work @omahane
