### PR TITLE
VACMS-13025: Adds null check

### LINKED ISSUE #13025: Ajax error on VAMC Facility Health Service
## Describe the defect
On the VAMC Facility Health Service content type, there are some fields that display when the editor clicks a button. For example, to add additional phone numbers or email address, there is a button and then additional fields to add this information will appear. However, currently there is an ajax error preventing this from working correctly.

## To Reproduce
1. In production or staging create a new [VAMC Facility Health Service](https://staging.cms.va.gov/node/add/health_care_local_health_service)
2. Scroll down to **Service Locations**
4. Expand **Contact Info**
5. Open the console
6. Click the **Add new phone number** or **Add new email address** button
7. Notice how either one of those shows an ajax error in the console

## AC / Expected behavior

- [ ] Clicking the Add new phone number button should display the appropriate fields
- [ ] Clicking the email address button should display the appropriate fields
- [ ] Cypress tests have been updated to test the AJAX call.

## Screenshots
**Fields that should be displayed when Phone number button is clicked**
image

**Fields that should be displayed when Email address button is clicked*
image

**Ajax error**
image

 ## Additional context
This same functionality is available on [VAMC Facility Non-clinical Service](https://staging.cms.va.gov/node/add/vha_facility_nonclinical_service) however, this is working correctly there.

I also found a [PR that was built 2 weeks](https://pr12874-wsqnjthrigy3btms8f0uv0ead6ogmowc.ci.cms.va.gov/node/add/health_care_local_health_service) ago that this is working correctly on

### Recent logs report:
The error seems to be in va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php
Line 22: Drupal\Core\Entity\EntityStorageBase->load(NULL)

The issue seems to be that no Section has been set yet, so it can't load the entity based on the null value.

Screen Shot 2023-03-21 at 9 09 33 AM

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #13025.

## Testing done
Manually
Cypress

## Screenshots
Screen Shot 2023-03-21 at 3 56 06 PM
Screen Shot 2023-03-21 at 3 59 40 PM

### Create new VAMC facility health service
- [x] Create [new VAMC facility health service](https://pr13027-mjhgn9zppigbzvtuomdnr5exa62yhfma.ci.cms.va.gov/node/add/health_care_local_health_service)
- [x] Click 'Add new phone number'
- [x] Validate that the phone number form fields display

### Edit VAMC facility health service
- [x] Log in as Ryan.Stubblebine@va.gov
- [x] Edit [My HealtheVet coordinator - Belmont County VA Clinic](https://pr12865-anjh0saa6ev6qhdgsr9wifu9sftbjnip.ci.cms.va.gov/node/2333/edit)
- [x] Click 'Add new phone number'
- [x] Validate that the phone number form fields display
- [x] Click "Add Service location"
- [x] Validate that "Address", "Hours", and "Contact info" fieldsets are loaded

#### Testing for a regression in the changed code
- [x] Change the Section to "---VA Lebanon health care" 
- [x] Click "Save draft and continue editing"
- [x] Validate that the Facility field presents a relevant error message
- [x] Validate that the VAMC system health service field presents a relevant error message
- [x] Change the Facility to "Berks County VA Clinic | VA Lebanon health care"
- [x] Click "Save draft and continue editing"
- [x] Validate that the VAMC system health service field presents a relevant error message
- [x] Change the Section to "---VA Pittsburgh health care"
- [x] Click "Save draft and continue editing"
- [x] Validate that the Facility field presents a relevant error message
- [x] Change the Facility to "Fayette County VA Clinic | VA Pittsburg health care"
- [x] Click "Save draft and continue editing"
- [x] Validate that the service is changed.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [x] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

File: docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php [hunk 1]
```diff
@@ -19,16 +19,19 @@ public function validate($items, Constraint $constraint) {
...
-      $referencedEntity = $nodeStorage->load($item->target_id);
-      if ($referencedEntity->field_administration->target_id !== $sectionTermID) {
-        /** @var \Drupal\va_gov_vamc\Plugin\Validation\Constraint\SectionMatcher $constraint */
-        $this->context->addViolation($constraint->notSectionMatch, [
-          '%section' => $sectionName,
-          '%fieldLabel' => $fieldLabel,
-        ]);
-        return;
+    // If the node is new, no Section has been set; so do not validate.
+    if (isset($sectionTermID)) {
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php:23]: This seems like an odd check.  The code itself sets this. 
image

So what is actually being checked is whether $sectionTermID is not NULL.  Which would fail the isset.  It is more explicit (better readability) to look for what you are actually trying to pivot on.  
```suggestion
    if (!empty($sectionTermID)) {
```

File: tests/cypress/integration/content_editing_vamc_facility_service.feature [hunk 2]
```diff
@@ -21,6 +21,11 @@ Scenario: Log in and create VAMC Facility Health Service as a Lovell editor
   Then I select option "Captain James A. Lovell Federal Health Care Center | Lovell Federal health care - TRICARE" from dropdown with selector "#edit-field-facility-location"
   Then I select option "Cardiology at Lovell Federal health care - TRICARE" from dropdown with selector "#edit-field-regional-health-service"
 
+# Phone number AJAX test
+  Then I click the "Add new phone number" button
+  And I wait "20" seconds
+  Then I should see an element with the selector "[data-drupal-selector*='edit-field-phone-numbers-paragraph-form-']"
+
```
Comment (swirtSJW) [inline tests/cypress/integration/content_editing_vamc_facility_service.feature:28]: Nice work on adding a test to cover it.

**Review by swirtSJW — CHANGES_REQUESTED** [review]
This is looking really good @omahane .  Just one suggestion.

File: tests/cypress/integration/content_editing_vamc_facility_service.feature (hunk 2 above)
Comment (omahane) [reply tests/cypress/integration/content_editing_vamc_facility_service.feature:28]: I just hope it's not flaky. It could be, depending on server response time; but this should be a sufficient wait.

**Comment by omahane** [comment]
@swirtSJW Great suggestion. I have committed your suggestion. I've also updated the comment to better match the code.

**Review by swirtSJW — APPROVED** [review]
Great work.
image
