### PR TITLE
VACMS-12303: add menu section for lovell menu items in parent list

### LINKED ISSUE #12303: Lovell UX debt - Parent Link dropdown has unclear hierarchy
## Describe the defect
As a CMS editor working on Lovell content, I need to assign the Parent Link for VAMC Detail Pages.

It is possible to nest menu items two levels under **Programs**, but because the TRICARE and VA sides are combined here, there are instances where there are two identically labelled items to chose between with no indication which is which.

Screenshot 2023-01-20 121354

## To Reproduce
1. Go to https://staging.cms.va.gov/ and log in as Katie.Yearley@va.gov
2. Got to the edit view of this test node https://staging.cms.va.gov/node/52805/edit
3. Scroll down to Menu Settings in right navigation and expand the drop down menu for Parent link
4. See two Gynecology Clinics that could be parents and not know which is TRICARE and which is VA

## AC / Expected behavior
At the very least, we need to have documentation around if the order of identical items is meaningfully determined and consistent (i.e. is TRICARE always above Lovell) or how to verify that an item has been added to the intended Parent.

Ideally there would be a holistic review of the how this functionality is implemented so we could understand the possibilities and trade off between users and technical limitations.

## Screenshots

screencapture-staging-cms-va-gov-node-52805-edit-2023-01-20-12_14_13

 ## Additional context

- #11790 also covers UX debt of the Parent Link field
- KB Article - https://prod.cms.va.gov/help/vamc/how-to-manage-vamc-navigation-aka-menus
- Similar to #11790, this dropdown is even more confusing and overwhelming for Drupal Content Admins
- Also note that Audiology and Speech TRICARE is currently nested under Audiology and Speech VA. That is a content error to address with the Lovell editors, but also demonstrates how confusing this whole experience is for users.

Screenshot 2023-01-20 125430

screencapture-staging-cms-va-gov-node-52586-edit-2023-01-20-12_05_04

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #12303 

## Testing done

Manual testing

## Screenshots

LOVELL - Parent select list before code change
Screenshot 2023-02-09 at 5 31 56 PM

LOVELL - Parent select list after code change
Screenshot 2023-02-09 at 5 32 19 PM

OTHER - Parent select list before code change
Screenshot 2023-02-09 at 5 52 31 PM

OTHER - Parent select list after code change
Screenshot 2023-02-09 at 5 52 45 PM

## QA steps

**Lovell Items**

- [x] Log into the site as an admin
- [x] Visit /admin/structure/menu/manage/lovell-federal-health-care (you'll be clicking edit for the menu items below)
- [x] In a separate browser window log in as Katie.Yearley@va.gov
- [x] Visit /node/53388/edit
- [x] Cross reference the list of menu options available in the **Parent link** field with the entire menu in your admin tab
- [x] Verify that the suffix added to each menu option in the **Parent link** field matches the **Menu Section** field for each menu item in your admin tab

**Other Items**

- [x] Log out as Katie.Yearley@va.gov
- [x] Log in as Samuel.Hudson@va.gov
- [x] Visit /node/23403/edit
- [x] Verify that the options for the Parent link are unchanged compared to the screenshot above

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### CODE REVIEW

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php [hunk 1]
```diff
@@ -9,6 +9,7 @@
 use Drupal\node\NodeForm;
 use Drupal\path_alias\AliasManagerInterface;
 use Drupal\va_gov_user\Service\UserPermsService;
+use Drupal\va_gov_lovell\LovellOps; // phpcs:ignore
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:12]: why phpcs ignore?

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php [hunk 2]
```diff
@@ -481,7 +508,8 @@ protected function disableMenuOptions(array &$form, string $form_id) {
   protected function getMenuItemType($alias) {
     $type = NULL;
     if ($alias) {
-      $type = $this->checkForDisabledParentWithChildren($alias)
+      $type = $this->checkForLovellSubSystem($alias)
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:511]: By setting this first, aren't we causing this to bypass any of the other handling that prevents detail pages from being put in certain parts of the menu?

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php [hunk 3]
```diff
@@ -421,6 +430,24 @@ protected function checkForTypeDisabledParent($alias) {
...
+   * @param string $alias
+   *   The current alias.
+   *
+   * @return string|null
+   *   A state of self::LOVELLSYS or NULL.
+   */
+  protected function checkForLovellSubSystem(string $alias) {
+    if ($alias === '/' . LovellOps::TRICARE_PATH
+      || $alias === '/' . LovellOps::VA_PATH) {
+      // By setting this value this item will be excluded.
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:445]: This comment is a bit out scope.  It is describing  how code someplace else is going to behave.  That comment or something similar should be near where the code is that is calling this function.

**Review by swirtSJW — COMMENTED** [review]
Looking good.  Only a couple questions/suggestions

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php (hunk 3 above)
Comment (JayDarnell) [reply docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:445]: Good suggestion.

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php (hunk 2 above)
Comment (JayDarnell) [reply docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:511]: This function sets the type based on the first check that evaluates to true. That type is returned to the calling function and then passed as a parameter to addAllowedParent. Because this type doesn't match any of the checks in that function, these items are not added to the menu which is the goal. There are only two menu items that would satisfy this first check, these are the menu items for the two subsystems which we don't want users to see.

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php [hunk 4]
```diff
@@ -258,6 +260,13 @@ protected function applyVamcMenuRulesForDetailPage(array &$form) {
       $alias = $this->getAliasFromUri($menu_item->get('link')->uri);
       if ($alias) {
         $subject_uuid = $parent_options_menu_ids[$menu_item->get('uuid')->value];
+        // The Lovell menu contains section information for each menu item.
```
Comment (omahane) [inline docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:263]: I think it would helpful to call out specifically that Lovell menu is the only one with this field `field_menu_section'`, which makes this only apply to Lovell.

**Review by omahane — CHANGES_REQUESTED** [review]
QA passes. I only think the comments need to be clearer (see Steve's suggestion and my own).

File: docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php (hunk 4 above)
Comment (JayDarnell) [reply docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php:263]: Good suggestion.

**Review by omahane — APPROVED** [review]
QA passes. The comment changes are great.
