### PR TITLE
VACMS-8033: Update flag word-wrap style.

### LINKED ISSUE #8033: Text in flags should not wrap
## Describe the defect

In certain tables, the Flags get split onto two lines. This affects Seven and Claro.

## To Reproduce
1. Go to https://clarodemo-x1iumxudopspquvg1n2h3ylucye7xlhp.demo.cms.va.gov/admin/content/flagged 

## Expected behavior

Flags should print on one line, without wrapping. 

## Screenshots 

Flagged_Content___VA_gov_CMS

## Proposed fix

At this stage it's fine if we only fix this in Claro. There may be a better way of doing this, but this works.

```
<span class="flag changed changed-title" style="
    white-space: nowrap;
    display: inline-block;
">Changed name</span>
```

Flagged_Content___VA_gov_CMS

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description
Closes #8033 .

## Testing done
viewed flags on smaller breakpoints and verified none wrapped.

## Screenshots
image

## QA steps

As CMS admin, I can 
1. visit the flag view (`/admin/content/flagged`) and
2. verify the flags do not break and wrap to multiple lines 
3. Then validate Acceptance Criteria from issue
- [x] Flags should print on one line, without wrapping.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kevwalsh** [comment]
I'm confused that the code changes is in Claro theme but the screenshot up top is in Seven. 

But i turned on Claro in this PR environment and it looks good, so QA Pass.

<details><summary>Screenshot</summary>

Flagged_Content___VA_gov_CMS


</details>

Should theming tickets be going to Tanner at this point for review? @swirtSJW

File: tests/behavioral/cypress/support/commands.js [hunk 1]
```diff
@@ -102,6 +102,7 @@ Cypress.Commands.add('iframe', { prevSubject: 'element' }, ($iframe, callback =
 });
 
 Cypress.Commands.add("type_ckeditor", (element, content) => {
+cy.get('#' + element);
```
Comment (kevwalsh) [inline tests/behavioral/cypress/support/commands.js:105]: this looks unrelated

Comment (ndouglas) [reply tests/behavioral/cypress/support/commands.js:105]: I added that to make tests involving that step more reliable, since the PR was failing.  See [this thread](https://dsva.slack.com/archives/CT4GZBM8F/p1644955610834389).

**Comment by msbtterswrth** [comment]
@kevwalsh with the launch of claro next week, I didn't feel like we should waste time fixing things in the 'old' theme anymore, so I just added it to the claro theme.

File: tests/behavioral/cypress/support/commands.js [hunk 2]
```diff
@@ -102,6 +102,7 @@ Cypress.Commands.add('iframe', { prevSubject: 'element' }, ($iframe, callback =
 });
 
 Cypress.Commands.add("type_ckeditor", (element, content) => {
+cy.wait(5000);
```
Comment (swirtSJW) [inline tests/behavioral/cypress/support/commands.js:105]:
```suggestion
  cy.wait(5000);
```

**Comment by msbtterswrth** [comment]
@swirtSJW Fixed, i _just now_ got the notification there was a change requested!

**Review by swirtSJW — APPROVED** [review]
