### PR TITLE
VACMS-6522 Add nightly facility scan for closed facilities

### LINKED ISSUE #6522: Scan nightly for facilities in the CMS but not in the FAPI
As facility data admin I need to be notified when we have facilities in the CMS that are no longer in the FAPI  (assumed closed) so that I can take appropriate action to process them in the CMS.

This scan should run on the periodic daily job after all the migrations run.

It will gather an array of all facility ids in FAPI  then gather all facilities that are in CMS and compare all facilities in CMS to those.
When a facility is found in the CMS that is not in FAPI it will set field_fapi_validate to "Not in Facility API" unless the field_fapi_validate is already set to "Closure complete"

### LINKED ISSUE #7604: Defect: facilities flagged 'removal complete' do not show on  /admin/content/flagged
## Describe the defect
The View at /admin/content/flagged is not showing flagged items if they are only flagged "Removal complete".
regardless of the filter setting for "Show "Removal complete"

## To Reproduce
1. Flag a facility "Removal complete"
2. Go to /admin/content/flagged
3. Change the "Show "Removal complete" to either "-any-' or 'True'
4. The facility you just flagged should show, but it does not.

## Expected behavior
1. Flag a facility "Removal complete"
2. Go to /admin/content/flagged
3. Change the "Show "Removal complete" to either "-any-' or 'True' and click Filter
4. The facility you just flagged should show.
5. Change the "Show "Removal complete" to either "False' and click Filter
4. The facility you just flagged should NOT show.

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Closes #6522.
Closes #7604.

## QA steps

1. Go to [tugboat dashboard](https://tugboat.vfs.va.gov/6201e523690c6845a797a810) and open terminal
2. run `drush va_gov_migrate:flag-missing-facilities`
   - [x]  Validate that ~134 facilities have been flagged
   
image

3. Go to https://pr7921-bh56u9lgmf8ud4rjyhxcbxqnan2fpgtv.ci.cms.va.gov/admin/content/flagged 
  - [x] validate that there are ~134 items flagged "removed from source"
  
image

   - [x] validate there is no filter related to "Removal complete"     this feature has been deprecated.

4. Click on the link to one of the facilities that has been flagged "removed from source"
   -  [x] Validate that the recent changes shows the time, date, and message of the flagging
   
image

5 Go to https://pr7921-bh56u9lgmf8ud4rjyhxcbxqnan2fpgtv.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=va_gov_migrate

   - [x] validate that an entry shows the bulk flagging event. (may not be present if too much time ellapses and it gets pushed out of the log.
   
image

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

File: docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php [hunk 1]
```diff
@@ -52,22 +105,221 @@ public function cleanRevs() {
...
+   * Performs a sanity count on the facility api data.
+   *
+   * @param int $count_fapi
+   *   A count of the facility api data returned.
+   *
+   * @return bool
+   *   TRUE if suspicious, FALSE otherwise.
+   */
+  protected function facilityCountSeemsFaulty($count_fapi): bool {
+    if ($count_fapi < 2000 || $count_fapi > 5000) {
```
Comment (JayDarnell) [inline docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php:318]: What are these numbers based on?

**Review by JayDarnell — DISMISSED** [review]

File: docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php (hunk 1 above)
Comment (swirtSJW) [reply docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php:318]: These are a wild guess.  There are 2400 facilties in the FAPI right now.   It is unlikely there will be 400 closures.  and 2500 additions.   This is just a rudimentary sanity check on the data.   example the FAPI mistakenly returns no facilities... or only cemeteries... we don't want to flag all the other facilities as a result of the blip.
