### PR TITLE
VACMS-14616: Fix use of returnless function in `eventFormHelpers.js`.

### LINKED ISSUE #14616: Fix code scanning alert - Use of returnless function
Tracking issue for:
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/security/code-scanning/6

### PR DESCRIPTION
**Pull request by ndouglas**
Closes #14616.

Previous code:

```javascript

  const operate = () => {
    requireCTA();
    includeRegistrationsBool.addEventListener("click", () => {
      toggleRegistrationElements();
    });
    toggleRegistrationElements();

    includeLocationItemsRadios.addEventListener("change", () => {
      toggleLocationElements();
    });
    toggleLocationElements();
  };

  Drupal.behaviors.vaGovEventFormHelpers = {
    attach() {
      document.addEventListener("DOMContentLoaded", operate());
    },
  };
```

This code does not work as expected, as written -- at least, not according to my tests.

First, the "DOMContentLoaded" event fires.
Second, this JavaScript code is executed, including the `operate()`.
Third, the event listener for `DOMContentLoaded` is added, but it doesn't call anything, since nothing was returned from `operate()`.

This works in its present form because DOMContentLoaded has already fired by the time the behavior is attached and `operate()` is executed. Therefore, it continues to work (in my testing) if you remove the `document.addEventListener('DOMContentLoaded',` part.

## QA Steps

- [ ] Go to `/node/add/event`.
- [ ] Verify that checking and unchecking "Include registration information" continues to show and unshow relevant fields.

### CODE REVIEW

File: docroot/modules/custom/va_gov_events/js/eventFormHelpers.js [hunk 1]
```diff
@@ -144,7 +144,7 @@
 
   Drupal.behaviors.vaGovEventFormHelpers = {
     attach: function attach() {
-      document.addEventListener("DOMContentLoaded", operate());
+      operate();
     }
   };
 })(Drupal);
```
Comment (ndouglas) [inline docroot/modules/custom/va_gov_events/js/eventFormHelpers.js:150]:
```suggestion
})(Drupal);

```

**Review by chri5tia — APPROVED** [review]
Seems to remove code that existed before current PW team, and doesn't look to affect any work that we have done.

**Comment by ndouglas** [comment]
Er, oops. I saw that this was approved and merged it from my phone 😑. Didn't see there was still a requested review from Daniel.
