### PR TITLE
VACMS-9923: fix display for Lovell sub-sections in user section block

### LINKED ISSUE #9923: CMS: Lovell sub-sections show in user section block
## Describe the defect
After logging in, a user is taken taken to their user page which displays a user-section-block.  Since the subsections under Lovell were added
image

The block displays the subsections separately
image

## To Reproduce
1. Login as admin (admins have access to all sections)
2. See the user section block.  Notice two entries for Lovell.

## AC / Expected behavior
Lovell and its subsections should only show under VHA not as their own sections unless an editor is only assined to those explicitly.

 ## Additional context
This is likley only affecting true admins and content admins who are assigned to VHA at the upper level, not on a VAMC system level.

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #9923 

## Testing done

Manual testing

## Screenshots

Logged in as an admin before:
Screen Shot 2022-11-01 at 2 49 40 PM

Logged in as an admin after the fix:
Screen Shot 2022-11-01 at 2 39 27 PM

Expanded:
Screen Shot 2022-11-01 at 2 40 01 PM

Logged in as a Lovell editor after the fix:
Screen Shot 2022-11-01 at 2 40 10 PM

## QA steps

As an admin user
- [ ] Log into the site and verify the user sections list doesn't display either Lovell subsection at the top level
- [ ] Expand the VHA item, scroll down to find Lovell and verify all 3 sections are properly displayed

As a Lovell editor (example: Katie.Yearley@va.gov
- [ ] Log into the site and verify the Lovell subsections are properly displayed under Lovell Federal health care

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CODE REVIEW

File: docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php [hunk 1]
```diff
@@ -146,6 +146,15 @@ public function build() {
           ];
           break;
 
+        case 7:
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php:149]: This looks good.  Please update the docblock to speak the new truth
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/66841c3d1f332903d5661337238e0f32535bc4b9/docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php#L114

Comment (swirtSJW) [reply docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php:149]: Also if you understand the reason why the cases only account for odd numbers, that would be good to explain... because I don't get that part.

Comment (JayDarnell) [reply docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php:149]: Ah yes, I can add notes about the odd numbers to the doc block. I found that particularly confusing when I first looked at the code. It boils down to the fact we build the tree in such a way that each valid link has a sub array called items which contains the child links.

**Review by swirtSJW — APPROVED** [review]
Nice work Jay.  Test out good.
image

Lovell shows like it should
image

And there are no notices.
image
