### PR TITLE
VACMS-13120: Add check and cleanup string to status moreinfo push.

### LINKED ISSUE #13120: Fix incorrect counting of characters on facility status moreinfo
## Describe the defect
On rare occasions (maybe twice per year) we get facility status pushes that fail to be accepted by lighthouse due to being over the 300 character limit.  On the CMS side we cut off at 300 characters (including html).   The failure point is largely around carriage returns.   

I believe when you have a carriage return the counter counts it as one character, but when we json encode it it becomes multiple characters.

## To Reproduce
1. Go to a VAMC facility  Enter 299 characters of text and then add one carriage return.  The counter will say "o remaining".
2. Save the node as published which will cause the notification to be queued.
3. Find the entry in the queue, do a character count on the contents of "payload"
4. If it is over 300, lighthouse will not accept it.

## AC / Expected behavior
- [ ] I expect there is no way for an editor to create a status message that won't get pushed
- [ ] I expect the limit of the charter count is changed from 300 to 295 

## Additional context
slack https://dsva.slack.com/archives/CT4GZBM8F/p1680059600954869

## Implementation thoughts

1. Reworking the contributed wysiwig counter to jsonencode the contents of the field in order to get an accurate count seems a bit extreme, but is one possibility.
2. Changing the text limit to 298 would likely solve most of the remaining times where this happens.  It would falsely limit the characters by 1% but is likely the simplest solution.

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #13120 

## Testing done
Manually

## Screenshots
string-length-300-plus-test-and-processing

### Editing the node
Screen Shot 2023-04-14 at 12 02 02 PM

### Checking the queue
Screen Shot 2023-04-14 at 12 02 22 PM

### When JSON Encoded text is more than 300
1. Edit [Richland VA Clinic](https://pr13287-vm1qqyifxta8wjri7dsntyutaxmsg9n0.ci.cms.va.gov/node/2257/edit).
2. Set the operating status to Facility Notice
3. Add the following to the Details, which should be counted as 297 characters, showing "3 characters remaining":
```
The Department of Veterans Affairs (VA) is a federal agency that provides healthcare, education and other benefits to Veterans.

The VA has over 370,000 employees and is the second largest federal employer. The VA has been has been praised for its high-quality care and its commitment to veterans.
```
4. Save the facility as Published
5. Check the [Post API Queue](https://pr13287-vm1qqyifxta8wjri7dsntyutaxmsg9n0.ci.cms.va.gov/admin/config/post-api/queue)
6. [ ] Validate that the character count of the "additional_info" of nid 2257 is less than 300 with no return or line break characters.

### When JSON Encoded text is less than 300
1. Edit [Lewiston VA Clinic](https://pr13287-vm1qqyifxta8wjri7dsntyutaxmsg9n0.ci.cms.va.gov/node/2253/edit).
2. Set the operating status to Facility Notice
3. Add the following to the Details, which should be counted as 207 characters, showing "93 characters remaining":
```
The Department of Veterans Affairs (VA) is a federal agency that provides healthcare, education and other benefits to Veterans.

The VA has over 370,000 employees and is the second largest federal employer. 
```
4. Save the facility as Published
5. Check the [Post API Queue](https://pr13287-vm1qqyifxta8wjri7dsntyutaxmsg9n0.ci.cms.va.gov/admin/config/post-api/queue)
6. [ ] Validate that the character count of the "additional_info" of nid 2253 is less than 300 but has retained its return and line break characters.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### CODE REVIEW

File: docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php [hunk 1]
```diff
@@ -169,7 +169,20 @@ protected function getPayload(bool $forcePush = FALSE): array {
...
+      // let's do our best to trim this down if we need to
+      if ($additionalInfoToPushLength > 300) {
+        $this->additionalInfoToPush = str_replace('&nbsp;', ' ', $this->facilityNode->get('field_operating_status_more_info')->value);
+        $this->additionalInfoToPush = trim($this->additionalInfoToPush);
+        $this->additionalInfoToPush = preg_replace("/(\r?\n|\r)+/", " ", $this->additionalInfoToPush);
+      }
+      else {
+        $this->additionalInfoToPush = $this->facilityNode->get('field_operating_status_more_info')->value;
+      }
+    }
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php:185]: Should:   Anytime we have have logic that is multiple control structures deep it is a good idea to move it to a well named method that clearly describes what is happening.

In this case it could be something like getOperatingStatusMoreInfoShort()

So then `$this->additionalInfoToPush = $this->getOperatingStatusMoreInfoShort();

Comment (swirtSJW) [reply docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php:185]: The logic itself looks greate.

Comment (omahane) [reply docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php]: That makes sense. I have refactored accordingly.

File: docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php [hunk 2]
```diff
@@ -192,6 +192,28 @@ protected function getPayload(bool $forcePush = FALSE): array {
...
+   * Get operating status details, shortened as necessary.
+   *
+   * @return string
+   *   Details of operating status.
+   */
+  protected function getOperatingStatusMoreInfoShort() : string {
+    if ($this->facilityNode->get('field_operating_status_more_info')->value) {
+      $operatingStatusMoreInfo = $this->facilityNode->get('field_operating_status_more_info')->value;
+      $operatingSatusMoreInfoLength = json_encode($this->facilityNode->get('field_operating_status_more_info')->value);
+      $operatingSatusMoreInfoLength = mb_strlen($operatingSatusMoreInfoLength);
```
Comment (swirtSJW) [inline docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php:205]: This one bit is deceiving, At this point it is not a length. yet we are calling it a lenght.  Feels like it should be something else.  Like this?
```suggestion
      $operatingSatusMoreInfoJson = json_encode($this->facilityNode->get('field_operating_status_more_info')->value);
      $operatingSatusMoreInfoLength = mb_strlen($operatingSatusMoreInfoJson);
```

**Comment by swirtSJW** [comment]
image
