### PR TITLE
VACMS-6115 Add perms so content_admin can create blocks

### LINKED ISSUE #6115: Content_admin can't create alert blocks, but content editors can
**Describe the defect**
As a content_admin, I am supposed to be allowed to create alert blocks @ `/block/add/alert`, but I get an access denied.
image

I found the issue.  Directly related to perms
image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Closes #6115 

## QA steps

As user with content_admin
1. go to https://pr6116-rlyrfwurdiqu9bbnt4utf2xuxleqg6ql.ci.cms.va.gov/block/add/alert
  - [ ] validate there is not access denied.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

File: tests/phpunit/Security/RolesPermissionsTest.php [hunk 1]
```diff
@@ -201,6 +203,7 @@ public function expectedPerms() {
         [
           'create vet_center_cap content',
           'create vet_center_facility_health_servi content',
+          'view node link report',
```
Comment (swirtSJW) [inline tests/phpunit/Security/RolesPermissionsTest.php:206]: Caught this one too while I was examining the roles.   Vet center editors need to see when they have broken links.

**Review by ethanteague — APPROVED** [review]
